### ISSUE TITLE
Could not generate CGImage for CIPalletize and CIKMeans filters

### ISSUE THREAD

**Issue by anupamchugh** [noahsark769/cifilter.io#107]

**Comment by noahsark769** [comment]
Hey @anupamchugh, sorry for the long delay on this and thanks for the report. I'm going to look into this and queue it for the next version of the app.

**Comment by noahsark769** [comment]
As it turns out, this seems to be a bug in iOS 13. I haven't been able to successfully use CIKMeans at all, but with the same inputs it works in iOS 14 beta. I've disabled the filter "Try It" button and linked to this issue for now.

**Comment by noahsark769** [comment]
(This will go out in the coming release)
