### ISSUE TITLE
Layout broken in commit 11824e0e

### ISSUE THREAD

**Issue by muizidn** [noahsark769/cifilter.io#125]
Unfortunately my iPhone doesn't support 13 yet. So I build the project for iOS12. Which the latest commit compatible to that version is 11824e0e.

But I got this issue.

![IMG_3055A76E6122-1](https://user-images.githubusercontent.com/19355715/87221578-4434a400-c397-11ea-9376-00e687157df1.jpeg)

Is this worth to fix 😄? Can I make a PR for this?
Thanks in advance.

**Comment by noahsark769** [comment]
Hi @muizidn, so sorry for the long delay in getting back to you. Sure, I'd accept a pull request for those who want to build the project to a device which doesn't support iOS 13. I've created a branch called `compatibility/ios-12`, feel free to make a PR to that if you'd like. Unfortunately I don't think I'll be able to maintain this branch (won't get any bug fixes) but would be happy to have it around in case anyone wants to build the app in a working state for iOS 12. This is actually my fault for not bumping the version at the correct time.

Thanks!

**Comment by noahsark769** [comment]
Going to close this issue since I think the branch in the above comment should address the concern here. Feel free to reach out if I can help any more with this use case!
