### ISSUE TITLE
iOS 14: back button disappears

### ISSUE THREAD

**Issue by noahsark769** [noahsark769/cifilter.io#132]
https://twitter.com/gaborthefisher/status/1308731479938281473?s=21

**Comment by regularberry** [comment]
This is caused by - https://github.com/noahsark769/cifilter.io/blob/5e517658dd580f86a3eb8988bcea5d8ef27c019f/iOS/CIFilter.io/Filter%20Detail/FilterDetailViewController.swift#L15

The Apple docs say "You use this property in classic split view interfaces only." - so I'm guessing it didn't survive the iOS update?

If you're ok with removing that button I can open a PR.

**Comment by noahsark769** [comment]
Hm, interesting. The reason why that button is there, I think, is that in regular-width interfaces like iPad portrait orientation, we want to have a button in the nav bar which opens the primary view controller of the split view controller. If that works correctly when removing that line, I'd be happy to accept a PR for it! Thanks for looking into this!

**Comment by regularberry** [comment]
Good call. You lose that button on the iPad when I remove it... not good.

I dug into this a little more and `navigationItem.leftItemsSupplementBackButton` gets turned from `true` to `false` in between `viewWillAppear` and `viewDidAppear` in the `UIHostingController`. 

* This doesn't happen on iOS 13.7, but it happens on iOS 14.1.  
* It doesn't happen on a regular `UIViewController`, only a `UIHostingController`
* It's not your SwiftUI view either, a trivial `Text("sup")` still causes it

One fix is to reenable that flag on `viewDidAppear`, but then there's a brief flash of the button after the view appears, which isn't ideal...

**Comment by noahsark769** [comment]
Huh, very interesting. We could try moving the code that sets the `leftBarButtonItem` and `leftItemsSupplementBackButton` entirely to `viewDidAppear`, and that might work things out? We'd have to grab the button from `self.splitViewController?.displayModeButtonItem` in that case, which might be nicer anyways since we wouldn't have to pass the `splitViewController` through the `FilterDetailViewController` initializer. I think in this case the button might not be displayed for a split second when the view controller first comes on screen, but I think that's probably okay, and since we wouldn't set it in the initializer there wouldn't be a flash of the button, I don't think.

I could be wrong though 🤷 

We could also try setting these in various places, like `viewDidAppear` and `viewDidLoad` instead of the init, but I'm not sure that that would help.

**Comment by noahsark769** [comment]
Fixed by #135
