### ISSUE TITLE
Use filters.json to generate a type-safe Swift CIFilter library

### ISSUE THREAD

**Issue by noahsark769** [noahsark769/cifilter.io#72]
This has been suggested by several people - since we have all the filter data, we could autogenerate Swift code for type-safe applications of the filters, instead of the current solution of string typing.

A good way to go about this could be to put the generated files in a new folder in this repo, and have a `TypeSafeCIFilter.podspec` in the root which references them

**Comment by shpakovski** [comment]
Hi, thanks a lot for building this tool! A full-featured library is a massive work, how about providing simple code syntax-highlighted snippets right on the website?

**Comment by noahsark769** [comment]
Definitely! Are you thinking of something like in #40?

**Comment by shpakovski** [comment]
Sounds great, yes!

**Comment by noahsark769** [comment]
As of iOS 13+, there seem to be classes available for each filter, e.g. [this one for CIBokehBlur](https://developer.apple.com/documentation/coreimage/cibokehblur?language=objc). Though the documentation is still in beta, it's reasonable to assume that these classes will take the place of any type-safe library that we would generate. Going to close this issue for now.
