### ISSUE TITLE
Floating point numbers cannot be entered

### ISSUE THREAD

**Issue by james-howard** [noahsark769/cifilter.io#73]
Steps to reproduce:

1. Select a filter that has floating point number inputs (I used CIBokehBlur)
2. Tap in text field for one of the floating point number inputs (I used inputRingAmount)
3. Try to enter a decimal

Results
Number input keyboard lacks a '.' button.

Expected Results
Keyboard has a '.' button. Maybe use UIKeyboardTypeDecimalPad instead of UIKeyboardTypeNumberPad?

![PNG image](https://user-images.githubusercontent.com/2006254/55651988-18436f80-579f-11e9-8c91-bd6bd07992a8.png)

**Comment by noahsark769** [comment]
Wow, @james-howard thanks for the great report! You're totally right, I was able to reproduce this. I'm going to put this in for the next release (or if you'd like to submit a PR feel free)
