### ISSUE TITLE
Search terms should match parameter names and descriptions

### ISSUE THREAD

**Issue by davedelong** [noahsark769/cifilter.io#76]
I'm searching for filters that take certain kinds of parameters (eg `aspectRatio`) and it'd be nice if searching would also search through the parameter names as well.

**Comment by noahsark769** [comment]
Great idea! I'm going to close #39 in favor of this, since this one is more descriptive.

**Comment by noahsark769** [comment]
![image](https://user-images.githubusercontent.com/1168853/57504080-e2b30a00-72a7-11e9-9fa5-54577be42b87.png)

I think this UI of putting a small tag next to the search result should probably do it! Fix will be merged soon 👍

**Comment by noahsark769** [comment]
@davedelong this is now live, thanks again for the suggestion!
